const QUEUESTATUS_PENDING = 'PENDING';
const QUEUESTATUS_IN_PROGRESS = 'IN PROGRESS';
const QUEUESTATUS_FAILED = 'FAILED';
const QUEUESTATUS_COMPLETED = 'FINISHED';

const SHARED_DRIVES_SHEET_NAME = 'drives';
const SHARED_DRIVES_PERMISSIONS_SHEET_NAME = 'drive permissions';
const SHARED_DRIVES_FOLDER_SHEET_NAME = 'folders';
